### ISSUE TITLE
关于将Resnet50蒸馏成Resnet18的尝试

### ISSUE THREAD

**Issue by myc1998** [megvii-research/ICD#4]
您好，最近我想将Resnet50蒸馏成Resnet18，但是在验证集上显示，模型并没有学到东西，AP值一直是零点几。
请问您在这个工程中做过相关类似的尝试吗？有什么经验分享吗？

**Comment by AmoseKang** [comment]
你可以介绍一下具体的设置，我们早期尝试过，是可以涨点的。一般调整蒸馏算法，首先要保证baseline稳定且效果合理，再添加蒸馏损失，如果想进一步增强性能，可以尝试调整蒸馏系数。

**Comment by myc1998** [comment]
可以分享下您设置的配置文件吗，我这边参考一下。确实我的设置在baseline上的效果就不好。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [megvii-research/ICD] 关于将Resnet50蒸馏成Resnet18的尝试 (Issue #4)




 
你可以介绍一下具体的设置，我们早期尝试过，是可以涨点的。一般调整蒸馏算法，首先要保证baseline稳定且效果合理，再添加蒸馏损失，如果想进一步增强性能，可以尝试调整蒸馏系数。

**Comment by AmoseKang** [comment]
你可以试试如下Baseline，蒸馏config应该不需要改变。请注意学习率，batch size和预训练权重。我们并不保证resnet18的蒸馏效果。
```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 'PATH_TO_WEIGHTS'
  # use detectron2/tools/convert.py to transfer:
  # https://download.pytorch.org/models/resnet18-f37072fd.pth
  MASK_ON: False
  #BACKBONE:
  #  FREEZE_AT: 0 # maybe enable this
  RESNETS:
    RES2_OUT_CHANNELS: 64
    DEPTH: 18
  # grad clip is also useful

```
